input_letter = input('暗号化する文を入れてください:')

print(input_letter
    .replace('a', 'b')
    .replace('b', 'c')
    .replace('c', 'd')
    .replace('d', 'e')
    .replace('e', 'f')
    .replace('f', 'g')
    .replace('g', 'h')
    .replace('h', 'i')
    .replace('i', 'j')
    .replace('j', 'k')
    .replace('k', 'l')
    .replace('l', 'm')
    .replace('m', 'n')
    .replace('n', 'o')
    .replace('o', 'p')
    .replace('p', 'q')
    .replace('q', 'r')
    .replace('r', 's')
    .replace('s', 't')
    .replace('t', 'u')
    .replace('u', 'v')
    .replace('v', 'w')
    .replace('w', 'x')
    .replace('x', 'y')
    .replace('y', 'z')
)